[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = "cancun"
fs_permissions = [{ access = "read", path = "./" }]

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/uniswap-hooks/lib/openzeppelin-contracts/contracts/",
    "@uniswap/v4-core/=lib/uniswap-hooks/lib/v4-core/",
    "@uniswap/v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/",
    "v4-core/=lib/uniswap-hooks/lib/v4-core/src/",
    "v4-periphery/=lib/uniswap-hooks/lib/v4-periphery/src/",
    "uniswap-hooks/=lib/uniswap-hooks/src/",
    "permit2/=lib/uniswap-hooks/lib/v4-periphery/lib/permit2/",
    "solmate/=lib/uniswap-hooks/lib/v4-core/lib/solmate/",
    "@reactive/=lib/reactive-lib/src/",
]

[rpc_endpoints]
unichain_sepolia = "${UNICHAIN_SEPOLIA_RPC}"
base_sepolia = "${BASE_SEPOLIA_RPC}"
reactive_lasna = "${REACTIVE_LASNA_RPC}"

[etherscan]
unichain_sepolia = { key = "${UNICHAIN_SEPOLIA_ETHERSCAN_KEY}", url = "https://sepolia.uniscan.xyz/api" }
base_sepolia = { key = "${BASESCAN_KEY}", url = "https://api-sepolia.basescan.org/api" }
